---
title: "Predicting Changing Zillow House Values in Newark, NJ"
subtitle: "By: Javier Fernandez"
---

## Project Purpose

The aim of this project was to extend the application of our housing prediction model to a new city: Newark, New Jersey. As the largest city in the state, Newark is strategically located with easy access to New York City through various transportation modes, making it an vital hub within New Jersey and the larger New York Metropolitan Area. Home to significant institutions like Rutgers University, the Prudential Center, and Newark Liberty International Airport, Newark also serves as a vital center for employment and opportunities.

However, in recent years, the city has witnessed a surge in development interest, accompanied by concerns among residents regarding escalating rents and an influx of wealthier populations. Thus, it became imperative to undertake this project, delving into the current dynamics of housing sales (or a proxy thereof) and crafting predictive models—both linear and random forest—that could anticipate changes in the Zillow Home Value Index (ZHVI) based on diverse sociodemographic factors.

Despite its limitations, this approach involved innovative techniques such as API utilization, ZHVI data aggregation from zip codes to census tracts, and comprehensive incorporation of crucial predictors at the census tract level. Moving forward, it's crucial to consideri refining the model by accessing more granular ZHVI data, ideally at the census tract or individual home-sale level. This project highlights the need for further investigation into Newark's changing real estate market and how it affects its residents, given the limited data available.

::: {.callout-important}
Datasets referenced: 
Zip Codes: https://data.ci.newark.nj.us/dataset/new-jersey-zip-codes-polygon

Zillow Data: https://www.zillow.com/research/data/

Census: referenced through its API
:::






 
